name: Dependabot auto merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: Dependabot auto merge
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve PR
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve "$PR_URL"

      - name: Mark PR to be automatically merged
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL"
