name: Label PR

on: [pull_request_target]

jobs:
  pr-labeler:
    name: Label PR
    runs-on: ubuntu-20.04
    steps:
      - name: Label PR from branch prefix
        uses: TimonVS/pr-labeler-action@v4.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR from files
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
